version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access1234
      MINIO_ROOT_PASSWORD: secret1234
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  db-data:
